---
- name: Install and Run Apache Kafka with Zookeeper on Docker
  hosts: kafka_vm  # Change this to your actual target VM's
  become: yes
  tasks:

    - name: Ensure Docker is running
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Set Docker host IP fact
      set_fact:
        docker_host_ip: "{{ ansible_default_ipv4.address }}"

    - name: Create a Docker network for Kafka and Zookeeper
      community.docker.docker_network:
        name: kafka_network
        state: present

    - name: Pull Zookeeper image
      community.docker.docker_image:
        name: confluentinc/cp-zookeeper:latest
        source: pull

    - name: Pull Kafka image
      community.docker.docker_image:
        name: confluentinc/cp-kafka:latest
        source: pull

    - name: Run Zookeeper container
      community.docker.docker_container:
        name: zookeeper
        image: "confluentinc/cp-zookeeper:latest"
        state: started
        restart_policy: always
        networks:
          - name: kafka_network
        ports:
          - "2181:2181"
        env:
          ZOOKEEPER_CLIENT_PORT: "2181"
          ZOOKEEPER_TICK_TIME: "2000"

    - name: Wait for Zookeeper to be ready
      ansible.builtin.wait_for:
        host: "{{ docker_host_ip }}"
        port: 2181
        delay: 15
        timeout: 90
      register: zookeeper_ready

    - name: Set Kafka broker ID based on inventory hostname
      set_fact:
        kafka_broker_id: "{{ (inventory_hostname == 'kafka_vm') | ternary('1', '2') }}"  # Adjust based on actual hostnames

    - name: Run Kafka container
      community.docker.docker_container:
        name: kafka
        image: "confluentinc/cp-kafka:latest"
        state: started
        restart_policy: always
        networks:
          - name: kafka_network
        ports:
          - "9092:9092"
        env:
          KAFKA_ZOOKEEPER_CONNECT: "10.0.2.8:2181,10.0.2.5:2181"
          KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://{{ docker_host_ip }}:9092"
          KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092"
          KAFKA_BROKER_ID: "{{ kafka_broker_id }}"
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "2"
      when: zookeeper_ready is succeeded

    - name: Create systemd service for Zookeeper
      copy:
        dest: /etc/systemd/system/zookeeper.service
        content: |
          [Unit]
          Description=Zookeeper Container
          Requires=docker.service
          After=docker.service

          [Service]
          Restart=always
          ExecStart=/usr/bin/docker start -a zookeeper
          ExecStop=/usr/bin/docker stop zookeeper

          [Install]
          WantedBy=multi-user.target

    - name: Create systemd service for Kafka
      copy:
        dest: /etc/systemd/system/kafka.service
        content: |
          [Unit]
          Description=Kafka Container
          Requires=docker.service
          After=docker.service

          [Service]
          Restart=always
          ExecStart=/usr/bin/docker start -a kafka
          ExecStop=/usr/bin/docker stop kafka

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Enable and start Zookeeper service
      systemd:
        name: zookeeper
        enabled: yes
        state: started

    - name: Enable and start Kafka service
      systemd:
        name: kafka
        enabled: yes
        state: started



